### ISSUE TITLE
add presentations and results from open_BEA/eGo^n workshop

### ISSUE THREAD

**Issue by gplssm** [gplssm/egon-website#84]
### Tasks

- [x] Separate page "Publications" into "Paper and reports" and "Presentations"
- [x] Basic layout of "Presentations"
- [x] use data `.yml` for collecting presentations
  ```
  Year:
    - Event:
        - Publication 1
            Title
            Author
            Link
  ```
- [ ] Design presentations with existing layout components
- [x] Add presentations to `.yml`
  > 2020 I "Neue Verbraucher und elektrische Flexbilitäten - Potentiale und Herausforderungen im Übertragungs- und Verteilnetz" I Online-Workshop der Projekte open_BEA und eGo_n 

  > Session A2: Forschungsfragen und Szenarien
  > Session B1: Elektrische Flexibilitäten 
  > Session B2: Das eGo_n Modellkonzept
  > Session C2: Sektorenkopplung in der Stromnetzmodellierung
  > Session D2: Verwertbarkeit der Projektergebnisse
